In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/financial_dataset.csv")
df.head()

,Year,Quarter,Company_ID,Revenue,Expenses,Operating_Income,Net_Income,Assets,Liabilities,Equity,...,Global_Economic_Score,Inflation_Rate,Exchange_Rate,Interest_Rate,Audit_Flag,Fraud_Flag,Market_Shock_Flag,Policy_Change_Flag,Target_Revenue_Next_Qtr,Target_Anomaly_Class
0,2015,1,CMP_001,229991.3061,212058.6555,17932.65064,10592.371030,531737.3791,171875.3048,359862.0743,...,0.212339,2.272775,64.585113,4.433938,0,0,0,0,232953.1703,0
1,2015,2,CMP_001,214801.5217,190523.2287,24278.29303,7500.653613,515383.5079,260626.2319,254757.2760,...,0.965632,6.658781,67.615344,2.781377,0,0,0,0,202861.8164,0
2,2015,3,CMP_001,231901.9884,185517.5190,46384.46937,36708.803230,705013.5932,365679.3493,339334.2438,...,0.921874,1.619448,64.899572,2.361818,0,0,0,0,226367.1549,0
3,2015,4,CMP_001,213291.5593,186390.8956,26900.66373,9867.709016,458385.1648,318465.2818,139919.8829,...,0.771270,1.518313,68.961643,2.926952,0,0,0,0,220837.2080,0
4,2016,1,CMP_001,210824.8234,185755.8298,25068.99357,9124.900899,690475.5294,452182.1340,238293.3953,...,0.040434,5.974640,62.772271,5.514692,0,0,0,0,210554.5643,0

In [3]:
df.shape

(2000, 30)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Year                     2000 non-null   int64
 1   Quarter                  2000 non-null   int64
 2   Company_ID               2000 non-null   str
 3   Revenue                  2000 non-null   float64
 4   Expenses                 2000 non-null   float64
 5   Operating_Income         2000 non-null   float64
 6   Net_Income               2000 non-null   float64
 7   Assets                   2000 non-null   float64
 8   Liabilities              2000 non-null   float64
 9   Equity                   2000 non-null   float64
 10  Cash_Flow                2000 non-null   float64
 11  EPS                      2000 non-null   float64
 12  ROE                      2000 non-null   float64
 13  ROA                      2000 non-null   float64
 14  Debt_to_Equity           2000 non-null   float64
 15  Stock_Price              2000 non-null   float64
 16  Volume_Traded            2000 non-null   int64
 17  News_Sentiment_Score     2000 non-null   float64
 18  Social_Media_Buzz        2000 non-null   int64
 19  Sector_Trend_Index       2000 non-null   float64
 20  Global_Economic_Score    2000 non-null   float64
 21  Inflation_Rate           2000 non-null   float64
 22  Exchange_Rate            2000 non-null   float64
 23  Interest_Rate            2000 non-null   float64
 24  Audit_Flag               2000 non-null   int64
 25  Fraud_Flag               2000 non-null   int64
 26  Market_Shock_Flag        2000 non-null   int64
 27  Policy_Change_Flag       2000 non-null   int64
 28  Target_Revenue_Next_Qtr  2000 non-null   float64
 29  Target_Anomaly_Class     2000 non-null   int64
dtypes: float64(20), int64(9), str(1)
memory usage: 468.9 KB

In [5]:
df.describe()

,Year,Quarter,Revenue,Expenses,Operating_Income,Net_Income,Assets,Liabilities,Equity,Cash_Flow,...,Global_Economic_Score,Inflation_Rate,Exchange_Rate,Interest_Rate,Audit_Flag,Fraud_Flag,Market_Shock_Flag,Policy_Change_Flag,Target_Revenue_Next_Qtr,Target_Anomaly_Class
count,2000.000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2.000000e+03,2.000000e+03,2.000000e+03,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.00000,2000.000000,2000.000000
mean,2019.500,2.500000,279599.185562,214617.704393,64981.481169,52369.409756,8.375147e+05,4.199070e+05,4.176077e+05,54822.465703,...,0.496568,4.416098,72.329675,5.994525,0.051000,0.02200,0.108000,0.11050,287553.277673,0.172500
std,2.873,1.118314,156772.882828,128662.839763,49398.717910,49629.983527,5.044078e+05,2.770725e+05,2.748794e+05,49820.403181,...,0.288965,2.033309,7.128863,2.310342,0.220053,0.14672,0.310458,0.31359,161593.768139,0.377909
min,2015.000,1.000000,48592.472840,38857.552680,-36587.949360,-56529.510690,1.151015e+05,3.757223e+04,4.895568e+04,-48594.349780,...,0.000098,1.001767,60.014948,2.001324,0.000000,0.00000,0.000000,0.00000,49500.404730,0.000000
25%,2017.000,1.750000,117227.955725,85924.466525,24506.715997,12348.897937,3.609458e+05,1.741930e+05,1.785117e+05,14826.672362,...,0.248435,2.643757,66.112217,3.951656,0.000000,0.00000,0.000000,0.00000,120133.276675,0.000000
50%,2019.500,2.500000,268768.539750,194572.644500,50324.940445,37865.749280,7.876691e+05,3.593409e+05,3.603166e+05,40648.880765,...,0.496499,4.397745,72.535432,6.036970,0.000000,0.00000,0.000000,0.00000,276293.880950,0.000000
75%,2022.000,3.250000,439360.640250,320219.405425,98214.054385,85815.340135,1.234938e+06,6.132875e+05,6.029166e+05,87821.124060,...,0.748914,6.171872,78.250589,7.951616,0.000000,0.00000,0.000000,0.00000,448997.708700,0.000000
max,2024.000,4.000000,557615.210400,477748.592400,221762.612000,214541.100000,2.088077e+06,1.328500e+06,1.379743e+06,212070.085700,...,0.999461,7.998687,84.993789,9.997279,1.000000,1.00000,1.000000,1.00000,601877.356200,1.000000

In [6]:
df.isnull().sum()

Year                       0
Quarter                    0
Company_ID                 0
Revenue                    0
Expenses                   0
Operating_Income           0
Net_Income                 0
Assets                     0
Liabilities                0
Equity                     0
Cash_Flow                  0
EPS                        0
ROE                        0
ROA                        0
Debt_to_Equity             0
Stock_Price                0
Volume_Traded              0
News_Sentiment_Score       0
Social_Media_Buzz          0
Sector_Trend_Index         0
Global_Economic_Score      0
Inflation_Rate             0
Exchange_Rate              0
Interest_Rate              0
Audit_Flag                 0
Fraud_Flag                 0
Market_Shock_Flag          0
Policy_Change_Flag         0
Target_Revenue_Next_Qtr    0
Target_Anomaly_Class       0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

In [9]:
df.columns

Index(['year', 'quarter', 'company_id', 'revenue', 'expenses',
       'operating_income', 'net_income', 'assets', 'liabilities', 'equity',
       'cash_flow', 'eps', 'roe', 'roa', 'debt_to_equity', 'stock_price',
       'volume_traded', 'news_sentiment_score', 'social_media_buzz',
       'sector_trend_index', 'global_economic_score', 'inflation_rate',
       'exchange_rate', 'interest_rate', 'audit_flag', 'fraud_flag',
       'market_shock_flag', 'policy_change_flag', 'target_revenue_next_qtr',
       'target_anomaly_class'],
      dtype='str')

In [10]:
df.dtypes

year                         int64
quarter                      int64
company_id                     str
revenue                    float64
expenses                   float64
operating_income           float64
net_income                 float64
assets                     float64
liabilities                float64
equity                     float64
cash_flow                  float64
eps                        float64
roe                        float64
roa                        float64
debt_to_equity             float64
stock_price                float64
volume_traded                int64
news_sentiment_score       float64
social_media_buzz            int64
sector_trend_index         float64
global_economic_score      float64
inflation_rate             float64
exchange_rate              float64
interest_rate              float64
audit_flag                   int64
fraud_flag                   int64
market_shock_flag            int64
policy_change_flag           int64
target_revenue_next_qtr    float64
target_anomaly_class         int64
dtype: object

In [11]:
df.to_csv("../data/cleaned/financial_dataset_cleaned.csv", index=False)